"""
Report Generator - Create markdown reports for lead prospecting results.

This module generates structured markdown reports containing:
- Summary statistics
- Individual lead profiles with all data
- Execution details
- Recommendations

STORY-184: Lead Prospecting Workflow
"""

import logging
from typing import List, Optional
from datetime import datetime
from pathlib import Path

from schemas_lead_prospecting import LeadProfile

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate markdown reports for lead prospecting results."""

    def __init__(self, output_dir: str = "docs/leads"):
        """
        Initialize report generator.

        Args:
            output_dir: Directory for output reports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        leads: List[LeadProfile],
        sectors: Optional[List[str]],
        months: int,
        min_score: float,
        execution_time: float,
        total_candidates: int,
        in_history: int,
        new_processed: int,
        disqualified_sanctions: Optional[List[dict]] = None,
    ) -> str:
        """
        Generate complete markdown report.

        Args:
            leads: List of qualified LeadProfile objects
            sectors: Target sectors
            months: Time window
            min_score: Minimum qualification score
            execution_time: Execution time in seconds
            total_candidates: Total CNPJs from PNCP
            in_history: CNPJs already in history
            new_processed: New CNPJs processed

        Returns:
            Path to generated report
        """
        date_str = datetime.now().strftime("%Y-%m-%d")
        report_path = self.output_dir / f"leads-{date_str}.md"

        with open(report_path, "w", encoding="utf-8") as f:
            # Header
            f.write(f"# Lead Prospecting Report - {date_str}\n\n")
            f.write("**Generated by:** *acha-leads workflow\n")
            f.write(
                f"**Parameters:** sectors={sectors or 'all'}, months={months}, min_score={min_score}\n"
            )
            f.write(f"**Execution Time:** {execution_time:.1f}s\n\n")

            # Summary
            f.write("## Summary\n\n")
            f.write("**Deduplication:**\n")
            f.write(f"- Total Candidates: {total_candidates}\n")
            f.write(f"- Already in History: {in_history}\n")
            f.write(f"- **NEW Leads Processed:** {new_processed}\n")
            f.write(f"- **NEW Qualified Leads:** {len(leads)}\n\n")

            if not leads:
                f.write("**No qualified leads found in this execution.**\n\n")
                f.write(
                    "Try lowering min_score or increasing time window (months).\n\n"
                )

            # Sanctions section (STORY-256 AC9)
            if disqualified_sanctions:
                f.write("## Empresas Sancionadas Encontradas\n\n")
                f.write(
                    f"**{len(disqualified_sanctions)} empresa(s) desqualificada(s)** por sanções ativas:\n\n"
                )
                f.write("| CNPJ | Razão Social | CEIS | CNEP | Motivo |\n")
                f.write("|------|-------------|------|------|--------|\n")
                for entry in disqualified_sanctions:
                    f.write(
                        f"| {entry['cnpj']} | {entry['company_name']} "
                        f"| {entry['ceis_count']} | {entry['cnep_count']} "
                        f"| {entry['reason']} |\n"
                    )
                f.write("\n")

            f.write("---\n\n")

            # Individual lead profiles
            for i, lead in enumerate(leads, 1):
                self._write_lead_profile(f, i, lead)
                f.write("---\n\n")

            # Execution details
            f.write("## Execution Details\n\n")
            f.write("**Performance:**\n")
            f.write(f"- Execution Time: {execution_time:.1f}s\n")
            f.write(f"- Candidates Analyzed: {total_candidates}\n")
            f.write(f"- Qualified Leads: {len(leads)}\n")
            f.write(f"- Disqualified (already in history): {in_history}\n")
            f.write(
                f"- Disqualified (low score): {new_processed - len(leads)}\n\n"
            )

            if leads:
                f.write("**Recommendations:**\n")
                # Top 3 by score
                top_leads = sorted(
                    leads, key=lambda lead: lead.qualification.overall_score, reverse=True
                )[:3]
                f.write(
                    "1. **High Priority:** Leads #"
                    + ", #".join(
                        str(leads.index(lead) + 1) for lead in top_leads
                    )
                    + " (scores: "
                    + ", ".join(f"{lead.qualification.overall_score:.1f}" for lead in top_leads)
                    + ")\n"
                )
                f.write(
                    "2. **Immediate Action:** Review leads with dependency ≥85%\n"
                )
                f.write(
                    f"3. **Follow-up:** Generate Excel with current opportunities in {sectors or 'relevant sectors'}\n\n"
                )

            f.write("---\n\n")
            f.write(f"**Generated:** {datetime.now().isoformat()}\n")
            f.write("**Workflow Version:** 1.0.0\n")
            f.write("**Squad:** Lead Prospecting Task Force\n")

        logger.info(f"Report generated: {report_path}")
        return str(report_path)

    def _write_lead_profile(self, f, index: int, lead: LeadProfile):
        """Write single lead profile to report."""
        f.write(
            f"## Lead #{index} - [NEW] {lead.company_name} ⭐ (Score: {lead.qualification.overall_score:.1f}/10)\n\n"
        )

        # Contact Data
        f.write("### Contact Data\n")
        f.write(f"- **Email:** {lead.contact_data.email or 'N/A'}\n")
        f.write(f"- **Phone:** {lead.contact_data.phone or 'N/A'}\n")
        if lead.contact_data.whatsapp:
            f.write(f"- **WhatsApp:** {lead.contact_data.whatsapp} ✅\n")
        f.write(f"- **Website:** {lead.contact_data.website or 'N/A'}\n\n")

        # Company Intelligence
        f.write("### Company Intelligence\n")
        f.write(f"- **CNPJ:** {lead.cnpj}\n")
        if lead.nome_fantasia:
            f.write(f"- **Nome Fantasia:** {lead.nome_fantasia}\n")
        f.write(f"- **Sector:** {', '.join(lead.sectors) if lead.sectors else 'N/A'}\n")
        f.write(f"- **Size:** {lead.company_data.porte}\n")
        f.write(f"- **Founded:** {lead.company_data.data_abertura}\n")
        f.write(f"- **Primary Activity:** {lead.company_data.cnae_principal}\n")

        # Sanctions status (STORY-256)
        if lead.sanctions_check is not None:
            if lead.is_sanctioned:
                f.write(f"- **Sanctions:** SANCTIONED (CEIS: {lead.sanctions_check.ceis_count}, CNEP: {lead.sanctions_check.cnep_count})\n")
            else:
                f.write("- **Sanctions:** Clean (verified CEIS + CNEP)\n")
        else:
            f.write("- **Sanctions:** Not checked\n")
        f.write("\n")

        # Procurement Profile
        f.write("### Procurement Profile\n")
        f.write(
            f"- **Dependency Score:** {lead.dependency_score.dependency_percentage:.1f}% 🎯 ({lead.dependency_score.dependency_level})\n"
        )
        f.write(
            f"- **Recent Wins:** {lead.dependency_score.contract_count} contracts\n"
        )
        f.write(
            f"- **Total Contract Value:** R$ {lead.dependency_score.total_contract_value:,.2f}\n"
        )

        # Last contract
        most_recent = max(lead.contracts, key=lambda c: c.contract_date)
        f.write(
            f"- **Last Win:** {most_recent.contract_date} - {most_recent.contract_object[:100]}... (R$ {most_recent.contract_value:,.2f})\n\n"
        )

        # Strategic Intelligence
        f.write("### Strategic Intelligence\n\n")
        f.write(f"{lead.intelligence.summary}\n\n")

        # Personalized Message
        f.write("### Personalized Outreach Message\n\n")
        f.write("```\n")
        sector_name = lead.sectors[0] if lead.sectors else "licitações públicas"
        f.write(f"Subject: Oportunidades de Licitação em {sector_name.title()} - SmartLic\n\n")
        f.write(f"{lead.personalized_message}\n")
        f.write("```\n\n")

        # Qualification Breakdown
        f.write("### Qualification Score Breakdown\n")
        q = lead.qualification
        f.write(
            f"- **Dependency:** {q.dependency_score:.1f}/10 ({lead.dependency_score.dependency_percentage:.0f}% - Weight: 40%)\n"
        )

        # Calculate days for activity score
        most_recent_date = max(lead.contracts, key=lambda c: c.contract_date).contract_date
        days_ago = (datetime.now().date() - most_recent_date).days
        f.write(
            f"- **Recent Activity:** {q.activity_score:.1f}/10 (Last win {days_ago} days ago - Weight: 20%)\n"
        )

        f.write(f"- **Sector Match:** {q.sector_match_score:.1f}/10 (Weight: 20%)\n")

        contact_desc = []
        if lead.contact_data.email:
            contact_desc.append("Email")
        if lead.contact_data.phone:
            contact_desc.append("Phone")
        if lead.contact_data.whatsapp:
            contact_desc.append("WhatsApp")
        contact_str = "+".join(contact_desc) if contact_desc else "None"

        f.write(
            f"- **Contact Quality:** {q.contact_quality_score:.1f}/10 ({contact_str} - Weight: 20%)\n"
        )
        f.write(f"- **Overall:** {q.overall_score:.1f}/10 ⭐\n\n")

    def generate_empty_report(
        self,
        sectors: Optional[List[str]],
        months: int,
        min_score: float,
        total_candidates: int,
        in_history: int,
    ) -> str:
        """
        Generate report when no new leads are found.

        Args:
            sectors: Target sectors
            months: Time window
            min_score: Minimum score
            total_candidates: Total CNPJs found
            in_history: All in history

        Returns:
            Path to generated report
        """
        date_str = datetime.now().strftime("%Y-%m-%d")
        report_path = self.output_dir / f"leads-{date_str}-empty.md"

        with open(report_path, "w", encoding="utf-8") as f:
            f.write(f"# Lead Prospecting Report - {date_str}\n\n")
            f.write("**Generated by:** *acha-leads workflow\n")
            f.write(
                f"**Parameters:** sectors={sectors or 'all'}, months={months}, min_score={min_score}\n\n"
            )

            f.write("## Summary\n\n")
            f.write("**No new leads found.**\n\n")
            f.write(f"- Total Candidates: {total_candidates}\n")
            f.write(f"- Already in History: {in_history}\n")
            f.write("- **NEW Leads:** 0\n\n")

            f.write("**Recommendations:**\n")
            f.write("1. Increase time window (try --months 18 or --months 24)\n")
            f.write("2. Lower qualification score (try --min-score 6.0)\n")
            f.write("3. Try different sectors\n")
            f.write(
                "4. Check lead history to review previously discovered companies\n\n"
            )

            f.write("---\n\n")
            f.write(f"**Generated:** {datetime.now().isoformat()}\n")

        logger.info(f"Empty report generated: {report_path}")
        return str(report_path)
