#!/usr/bin/env python3
"""
check_module_coverage.py — AC5 of DEBT-111

Reads the .coverage database generated by pytest-cov and checks per-module
coverage against defined thresholds. Exits with code 1 if any threshold is
violated.

Uses coverage.Coverage + analysis() to get accurate executed/total line counts
(not just executed lines — CoverageData.lines() alone doesn't give the total).

Usage:
    cd backend
    python scripts/check_module_coverage.py [--coverage-file .coverage]
"""

import argparse
import os
import sys

# ---------------------------------------------------------------------------
# Threshold definitions
# ---------------------------------------------------------------------------
# Each entry maps a human-readable group name to:
#   - "files": list of source file paths (relative to backend/) to aggregate
#   - "threshold": minimum required line coverage percentage
# ---------------------------------------------------------------------------
MODULE_THRESHOLDS: dict[str, dict] = {
    "auth": {
        "files": [
            "auth.py",
            "authorization.py",
        ],
        "threshold": 60.0,
    },
    "billing": {
        "files": [
            "services/billing.py",
            "webhooks/stripe.py",
            "routes/billing.py",
        ],
        "threshold": 60.0,
    },
    "search_pipeline": {
        "files": [
            "search_pipeline.py",
            "consolidation.py",
            "search_context.py",
        ],
        "threshold": 60.0,
    },
}

# ANSI colour helpers (degrade gracefully if terminal doesn't support them)
_USE_COLOUR = sys.stdout.isatty() or os.environ.get("FORCE_COLOR") == "1"


def _green(text: str) -> str:
    return f"\033[32m{text}\033[0m" if _USE_COLOUR else text


def _red(text: str) -> str:
    return f"\033[31m{text}\033[0m" if _USE_COLOUR else text


def _bold(text: str) -> str:
    return f"\033[1m{text}\033[0m" if _USE_COLOUR else text


# ---------------------------------------------------------------------------
# Coverage data extraction
# ---------------------------------------------------------------------------

def load_coverage(coverage_file: str):
    """Load a coverage.Coverage object pointing at the given data file.

    Returns a (coverage.Coverage, {norm_path: (executed, total)}) tuple or
    raises SystemExit on error.

    We use coverage.Coverage.analysis2() per file rather than CoverageData
    directly so we get accurate total-line counts (not just executed lines).
    """
    try:
        import coverage as coverage_pkg  # type: ignore[import]
    except ImportError:
        print(
            "ERROR: 'coverage' package not found.\n"
            "       Install it with: pip install coverage",
            file=sys.stderr,
        )
        sys.exit(2)

    if not os.path.exists(coverage_file):
        print(
            f"ERROR: Coverage data file not found: {coverage_file}\n"
            "       Run pytest with --cov first to generate it.\n"
            "       Example:  pytest --cov=. tests/",
            file=sys.stderr,
        )
        sys.exit(2)

    try:
        cov = coverage_pkg.Coverage(data_file=coverage_file)
        cov.load()
    except Exception as exc:  # noqa: BLE001
        print(
            f"ERROR: Failed to load coverage data from '{coverage_file}': {exc}",
            file=sys.stderr,
        )
        sys.exit(2)

    # Build a lookup: normalised absolute path -> (lines_executed, lines_total)
    file_stats: dict[str, tuple[int, int]] = {}
    try:
        measured = cov.get_data().measured_files()
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: Could not read measured files: {exc}", file=sys.stderr)
        sys.exit(2)

    for path in measured:
        try:
            # analysis2 returns (filename, stmts, excluded, missing, formatted_missing)
            _fn, stmts, _excluded, missing, _fmt = cov.analysis2(path)
            executed = len(stmts) - len(missing)
            total = len(stmts)
            file_stats[os.path.normcase(os.path.abspath(path))] = (executed, total)
        except Exception:  # noqa: BLE001
            # If analysis fails for a file, skip it (file may be deleted, etc.)
            pass

    return file_stats


def resolve_file_stats(
    file_stats: dict[str, tuple[int, int]],
    group_files: list[str],
    base_dir: str,
) -> tuple[int, int, list[str]]:
    """Aggregate line stats for all files in a group.

    Returns (lines_executed, lines_total, missing_files) where missing_files
    are relative paths not found in the coverage database.
    """
    total_executed = 0
    total_lines = 0
    missing_files: list[str] = []

    for rel_path in group_files:
        abs_path = os.path.normcase(
            os.path.abspath(os.path.join(base_dir, rel_path))
        )

        stats = file_stats.get(abs_path)

        # Fallback: suffix match (handles rare path normalisation mismatches)
        if stats is None:
            suffix = os.path.normcase(rel_path.replace("/", os.sep))
            for measured_path, s in file_stats.items():
                if measured_path.endswith(os.sep + suffix) or measured_path.endswith(suffix):
                    stats = s
                    break

        if stats is None:
            missing_files.append(rel_path)
            continue

        total_executed += stats[0]
        total_lines += stats[1]

    return total_executed, total_lines, missing_files


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check per-module coverage thresholds against .coverage database.",
    )
    parser.add_argument(
        "--coverage-file",
        default=".coverage",
        metavar="PATH",
        help="Path to the .coverage data file (default: .coverage)",
    )
    parser.add_argument(
        "--base-dir",
        default=None,
        metavar="DIR",
        help=(
            "Backend source root (default: parent of the scripts/ directory, "
            "i.e. backend/)"
        ),
    )
    args = parser.parse_args()

    # Resolve base dir: script lives at backend/scripts/check_module_coverage.py
    if args.base_dir:
        base_dir = os.path.abspath(args.base_dir)
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        base_dir = os.path.dirname(script_dir)  # backend/

    coverage_file = args.coverage_file
    if not os.path.isabs(coverage_file):
        coverage_file = os.path.join(base_dir, coverage_file)

    file_stats = load_coverage(coverage_file)

    print(_bold("\n=== Per-Module Coverage Check (DEBT-111 AC5) ===\n"))
    print(f"Coverage file : {coverage_file}")
    print(f"Backend root  : {base_dir}\n")

    # Table layout constants
    col_module = 20
    col_files = 32
    col_actual = 10
    col_thresh = 12
    col_status = 8

    header = (
        f"{'Module':<{col_module}} "
        f"{'Files':<{col_files}} "
        f"{'Actual%':>{col_actual}} "
        f"{'Threshold%':>{col_thresh}} "
        f"{'Status':>{col_status}}"
    )
    separator = "-" * len(header)

    print(header)
    print(separator)

    failures: list[str] = []

    for group_name, config in MODULE_THRESHOLDS.items():
        group_files: list[str] = config["files"]
        threshold: float = config["threshold"]

        executed, total, missing = resolve_file_stats(file_stats, group_files, base_dir)

        if total == 0:
            pct = 0.0
            note = " (no data)"
        else:
            pct = 100.0 * executed / total
            note = ""

        passed = pct >= threshold
        status_str = _green("PASS") if passed else _red("FAIL")
        pct_str = f"{pct:.1f}%{note}"

        if not passed:
            failures.append(group_name)

        # One row per file; first row carries the module summary columns
        for i, rel_file in enumerate(group_files):
            prefix = group_name if i == 0 else ""
            suffix_actual = pct_str if i == 0 else ""
            suffix_thresh = f"{threshold:.1f}%" if i == 0 else ""
            suffix_status = status_str if i == 0 else ""
            missing_marker = " [NOT FOUND]" if rel_file in missing else ""

            print(
                f"{prefix:<{col_module}} "
                f"{rel_file + missing_marker:<{col_files}} "
                f"{suffix_actual:>{col_actual}} "
                f"{suffix_thresh:>{col_thresh}} "
                f"{suffix_status:>{col_status}}"
            )

        print()  # blank line between groups

    print(separator)

    if failures:
        print(
            _red(
                f"\nFAILED: {len(failures)} module group(s) below threshold: "
                + ", ".join(failures)
            )
        )
        print(
            "Improve test coverage for the listed modules and re-run pytest --cov=.\n"
        )
        return 1

    print(_green("\nAll module coverage thresholds passed.\n"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
