name: server-action-bugfix-squad
version: 1.0.0
description: Squad for investigating and fixing Server Action authentication bugs
author: Tiago Sasaki
license: MIT
slashPrefix: server-action-bugfix
aios:
  minVersion: 2.1.0
  type: squad
components:
  tasks:
    - analyze-logs.md
    - trace-server-action.md
    - check-deployment-state.md
    - identify-root-cause.md
    - fix-server-action-mismatch.md
    - update-auth-flow.md
    - add-error-handling.md
    - implement-cache-bust.md
    - run-tests.md
    - validate-auth-flow.md
    - deploy-hotfix.md
    - monitor-production.md
  agents:
    - bug-investigator.md
    - hotfix-developer.md
    - deployment-validator.md
  workflows: []
  checklists: []
  templates: []
  tools: []
  scripts: []
config:
  extends: extend
  coding-standards: ../../docs/framework/CODING-STANDARDS.md
  tech-stack: ../../docs/framework/TECH-STACK.md
  source-tree: ../../docs/framework/SOURCE-TREE.md
dependencies:
  node: []
  python: []
  squads: []
tags:
  - custom
blueprint:
  source:
    - Current conversation context - Server Action authentication bug
  created_at: "2026-02-11T15:47:00Z"
  confidence: 0.89
