/**
 * Type definitions for BidIQ Uniformes POC
 *
 * STORY-222: API response types are now generated from the backend OpenAPI schema.
 * This file re-exports those types for backward compatibility and defines
 * frontend-only types (UI state, form validation, etc.)
 *
 * To regenerate API types: npm run generate:api-types
 */

import type { components } from "./api-types.generated";

// ============================================================================
// API Response Types — re-exported from generated OpenAPI types
// ============================================================================

/** Strategic executive summary from GPT-4.1-nano (from backend ResumoEstrategico schema) */
export type Resumo = components["schemas"]["ResumoEstrategico"];

/** Actionable recommendation for a specific procurement opportunity */
export type Recomendacao = components["schemas"]["Recomendacao"];

/** Breakdown of filter rejection reasons */
export type FilterStats = components["schemas"]["FilterStats"];

/** Individual bid item for display in search results */
export type LicitacaoItem = components["schemas"]["LicitacaoItem"];

/** InMail message response */
export type MessageResponse = components["schemas"]["MessageResponse"];

/** Conversation summary for list views */
export type ConversationSummary = components["schemas"]["ConversationSummary"];

/** Full conversation with messages thread */
export type ConversationDetail = components["schemas"]["ConversationDetail"];

/** Paginated list of conversations */
export type ConversationsListResponse = components["schemas"]["ConversationsListResponse"];

/** Unread message count for badge display */
export type UnreadCountResponse = components["schemas"]["UnreadCountResponse"];

// ============================================================================
// BuscaResult — frontend representation of backend BuscaResponse
// ============================================================================

/**
 * API response from POST /api/buscar.
 *
 * STORY-222: Based on generated BuscaResponse but with frontend-specific
 * fields (download_id is generated by the proxy, not the backend).
 */
export interface BuscaResult {
  resumo: Resumo;
  licitacoes: LicitacaoItem[];
  /** Download ID from frontend proxy filesystem cache (may be null) */
  download_id: string | null;
  /** Signed URL from object storage (preferred delivery, 60min TTL) */
  download_url?: string | null;
  total_raw: number;
  total_filtrado: number;
  filter_stats: FilterStats | null;
  termos_utilizados: string[] | null;
  stopwords_removidas: string[] | null;
  excel_available: boolean;
  upgrade_message: string | null;
  /** Per-source metrics when multi-source is active */
  source_stats: SourceStat[] | null;
  /** Number of bids with partial matches hidden by min match floor */
  hidden_by_min_match?: number | null;
  /** True if the min match filter was relaxed due to zero results */
  filter_relaxed?: boolean | null;
  /** Term validation metadata (new format for ignored terms) */
  metadata?: TermValidationMetadata | null;
  /** ISO timestamp of when search results were generated */
  ultima_atualizacao?: string | null;
  /** STORY-252 AC21-AC23: True when not all data sources responded */
  is_partial?: boolean;
  /** STORY-252 AC21: Per-source status for degradation details */
  data_sources?: DataSourceStatus[];
  /** STORY-252 AC22: Human-readable reason for degradation */
  degradation_reason?: string;
}

// ============================================================================
// Frontend-Only Types (not in backend schema)
// ============================================================================

/** Brazilian state codes (UFs) */
export const UFS = [
  "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
  "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
  "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
] as const;

export type UF = (typeof UFS)[number];

/** Search parameters for PNCP API */
export interface SearchParams {
  ufs: string[];
  data_inicial: string; // YYYY-MM-DD format
  data_final: string;   // YYYY-MM-DD format
  setor_id: string;     // Sector ID (e.g., "vestuario")
}

/** Available procurement sector */
export interface Setor {
  id: string;
  name: string;
  description: string;
}

/** Per-source fetch metrics (multi-source mode) */
export interface SourceStat {
  source_code: string;
  record_count: number;
  duration_ms: number;
  error: string | null;
  status: string;
}

/** Per-source status for degradation banners (STORY-252 AC21-AC23) */
export interface DataSourceStatus {
  source: string;
  status: "ok" | "timeout" | "error" | "skipped";
  records: number;
}

/** Validation metadata for search terms */
export interface TermValidationMetadata {
  termos_utilizados: string[];
  termos_ignorados: string[];
  motivos_ignorados: Record<string, string>;
}

/** Form validation errors */
export interface ValidationErrors {
  ufs?: string;
  data_inicial?: string;
  data_final?: string;
  date_range?: string;
}

// ============================================================================
// InMail Messaging Types (frontend-only type aliases)
// ============================================================================

export type ConversationCategory = "suporte" | "sugestao" | "funcionalidade" | "bug" | "outro";
export type ConversationStatus = "aberto" | "respondido" | "resolvido";
