name: bug-investigation-squad
version: 1.0.0
description: Squad for investigating and fixing persistent bugs in export, persistence, billing, and search quality
author: Tiago Sasaki
license: MIT
slashPrefix: bug-investigation
aios:
  minVersion: 2.1.0
  type: squad
components:
  tasks:
    - trace-export-path.md
    - diagnose-404-root-cause.md
    - validate-api-credentials.md
    - fix-export-endpoint.md
    - test-export-flow.md
    - verify-export-fix.md
    - trace-save-flow.md
    - debug-database-writes.md
    - validate-header-state.md
    - fix-search-persistence.md
    - test-saved-searches.md
    - verify-header-display.md
    - trace-billing-flow.md
    - audit-credit-transactions.md
    - debug-debit-logic.md
    - fix-billing-sync.md
    - test-credit-debit.md
    - verify-balance-accuracy.md
    - analyze-search-algorithm.md
    - audit-llm-decisions.md
    - identify-false-positives.md
    - identify-false-negatives.md
    - tune-relevance-scoring.md
    - verify-search-quality.md
  agents:
    - export-investigator.md
    - persistence-detective.md
    - billing-auditor.md
    - search-quality-analyst.md
  workflows: []
  checklists: []
  templates: []
  tools: []
  scripts: []
config:
  extends: extend
  coding-standards: ../../docs/framework/CODING-STANDARDS.md
  tech-stack: ../../docs/framework/TECH-STACK.md
  source-tree: ../../docs/framework/SOURCE-TREE.md
dependencies:
  node: []
  python: []
  squads: []
tags:
  - custom
blueprint:
  source:
    - Verbal description - Export 404, Search persistence, Billing debit, Search quality bugs
  created_at: 2026-02-10T00:00:00.000Z
  confidence: 0.9
