#!/usr/bin/env python3
"""
Dispatch Squad — Build Domain Registry (Auto-Discovery)

Scans the ENTIRE project ecosystem to build domain-registry.yaml automatically.
No hardcoded paths. Works with or without .aios-core/.

Scan targets:
  1. squads/*/config.yaml + agents/ + tasks/ + data/
  2. .aios-core/development/agents/ + tasks/
  3. .aios-core/marketing/tasks/
  4. .claude/commands/ (loose skills)

Output: squads/dispatch/data/domain-registry.yaml
  - AUTO-GENERATED section (rebuilt every run)
  - MANUAL OVERRIDES section (preserved between runs)

Usage:
    python squads/dispatch/scripts/build-domain-registry.py
    python squads/dispatch/scripts/build-domain-registry.py --dry-run
    python squads/dispatch/scripts/build-domain-registry.py --project-root /path
"""

import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False


# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

HEADER = """# ═══════════════════════════════════════════════════════════════════════════════
# DOMAIN REGISTRY — Auto-generated by build-domain-registry.py
# DO NOT EDIT the auto-generated section. Use manual-overrides.yaml for custom entries.
# Re-run: python squads/dispatch/scripts/build-domain-registry.py
# Generated: {timestamp}
# ═══════════════════════════════════════════════════════════════════════════════
"""

# Keywords extracted from directory/file names to build trigger lists
DOMAIN_KEYWORD_MAP = {
    "copy": {
        "primary": ["newsletter", "email", "copy", "headline", "sales page", "bullets", "lead magnet", "cta", "subject line"],
        "secondary": ["escrever", "criar texto", "conteúdo", "persuasion", "offer"],
    },
    "curator": {
        "primary": ["curadoria", "mining", "transcript mining", "momentos", "corte"],
        "secondary": ["curator", "video editing", "cuts"],
    },
    "design": {
        "primary": ["design system", "component", "token", "accessibility", "UI", "UX", "a11y"],
        "secondary": ["atom", "molecule", "organism", "Storybook", "Tailwind"],
    },
    "dispatch": {
        "primary": ["dispatch", "parallel", "wave", "batch execution"],
        "secondary": ["subagent", "pipeline", "cost optimization"],
    },
    "etl": {
        "primary": ["ETL", "extract", "collect", "harvest", "scrape", "download"],
        "secondary": ["data source", "web scraping", "youtube download"],
    },
    "squad-creator": {
        "primary": ["squad", "agent", "create-agent", "clone", "mind", "task definition"],
        "secondary": ["create-squad", "framework extraction", "DNA"],
    },
    "mmosMapper": {
        "primary": ["mind map", "cognitive analysis", "identity", "emulator", "synthesis"],
        "secondary": ["thinking DNA", "mental model", "persona"],
    },
}

# Default enrichment levels per domain type
ENRICHMENT_DEFAULTS = {
    "copy": "FULL",
    "curator": "STANDARD",
    "design": "STANDARD",
    "dispatch": "MINIMAL",
    "etl": "STANDARD",
    "squad-creator": "FULL",
    "mmosMapper": "FULL",
}

# Default model per domain type
MODEL_DEFAULTS = {
    "copy": "haiku",
    "curator": "sonnet",
    "design": "haiku",
    "dispatch": "haiku",
    "etl": "haiku",
    "squad-creator": "sonnet",
    "mmosMapper": "sonnet",
}

# .aios-core agent-to-domain mapping
AIOS_AGENT_DOMAINS = {
    "dev": {
        "triggers_primary": ["code", "function", "refactor", "bug", "feature", "component", "API", "endpoint", "implement", "script"],
        "triggers_secondary": ["class", "method", "module", "package", "import", "test"],
        "enrichment": "STANDARD",
        "model": "haiku",
    },
    "architect": {
        "triggers_primary": ["architecture", "PRD", "system design", "migration", "infrastructure", "database schema"],
        "triggers_secondary": ["trade-off", "decision", "pattern", "microservice"],
        "enrichment": "FULL",
        "model": "sonnet",
        "note": "Architecture tasks usually should NOT be dispatched — redirect to /architect",
    },
    "qa": {
        "triggers_primary": ["test", "QA", "validation", "coverage", "regression", "acceptance", "smoke test"],
        "triggers_secondary": ["assert", "verify", "check", "audit"],
        "enrichment": "STANDARD",
        "model": "sonnet",
    },
    "analyst": {
        "triggers_primary": ["analisar", "analyze", "relatório", "report", "métrica", "dashboard", "benchmark"],
        "triggers_secondary": ["dados", "data", "research", "insight"],
        "enrichment": "STANDARD",
        "model": "sonnet",
    },
    "ac-automation": {
        "triggers_primary": ["activecampaign", "ac", "tag", "lista", "automação", "contato", "automation"],
        "triggers_secondary": ["crm", "email marketing", "segment"],
        "enrichment": "STANDARD",
        "model": "haiku",
        "note": "MCP tasks must run foreground (MCP unavailable in background)",
        "kb_files": ["MCPs/activecampaign/CLAUDE.md"],
    },
    "bh-automation": {
        "triggers_primary": ["beehiiv", "bh", "subscriber", "post beehiiv", "segmento"],
        "triggers_secondary": ["newsletter platform"],
        "enrichment": "STANDARD",
        "model": "haiku",
        "note": "MCP tasks must run foreground (MCP unavailable in background)",
        "kb_files": ["MCPs/beehiiv/CLAUDE.md"],
    },
    "youtube": {
        "triggers_primary": ["youtube", "transcrição", "transcript", "timestamp", "vídeo"],
        "triggers_secondary": ["live", "mining", "video"],
        "enrichment": "STANDARD",
        "model": "haiku",
    },
    "data-engineer": {
        "triggers_primary": ["ETL", "pipeline", "schema", "database", "migration", "data model"],
        "triggers_secondary": ["transform", "extract", "load", "SQL"],
        "enrichment": "STANDARD",
        "model": "sonnet",
    },
    "pm": {
        "triggers_primary": ["PRD", "product", "roadmap", "prioritization"],
        "triggers_secondary": ["requirement", "feature request", "backlog"],
        "enrichment": "STANDARD",
        "model": "sonnet",
        "note": "PM tasks usually should NOT be dispatched — redirect to /pm",
    },
    "po": {
        "triggers_primary": ["story", "user story", "acceptance criteria", "grooming"],
        "triggers_secondary": ["epic", "backlog item", "sprint"],
        "enrichment": "STANDARD",
        "model": "sonnet",
        "note": "PO tasks usually should NOT be dispatched — redirect to /po",
    },
    "sm": {
        "triggers_primary": ["sprint", "retrospective", "standup", "facilitation"],
        "triggers_secondary": ["blocker", "velocity", "burndown"],
        "enrichment": "MINIMAL",
        "model": "sonnet",
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# SCANNING FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

def read_yaml_safe(path: Path) -> dict:
    """Read YAML file, returning empty dict on any error."""
    if not path.exists():
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if HAS_YAML:
            return yaml.safe_load(content) or {}
        # Fallback: extract name/description with regex
        result = {}
        m = re.search(r'^name:\s*(.+)$', content, re.MULTILINE)
        if m:
            result["name"] = m.group(1).strip()
        m = re.search(r'description:\s*[>|]?\s*\n?\s*(.+?)(?:\n\S|\Z)', content, re.DOTALL)
        if m:
            result["description"] = m.group(1).strip()
        return result
    except Exception:
        return {}


def scan_dir_names(directory: Path, ext: str = ".md") -> list[str]:
    """Return sorted list of file stems in a directory."""
    if not directory.exists():
        return []
    return sorted(f.stem for f in directory.glob(f"*{ext}") if f.is_file())


def find_kb_files(data_dir: Path, project_root: Path) -> list[str]:
    """Find knowledge base files (*.md, *.yaml) in a data directory."""
    if not data_dir.exists():
        return []
    kb_files = []
    for ext in ("*.md", "*.yaml"):
        for f in sorted(data_dir.glob(ext)):
            kb_files.append(str(f.relative_to(project_root)).replace("\\", "/"))
    return kb_files


def scan_squads(project_root: Path) -> dict:
    """Scan squads/ directory for all squad domains."""
    squads_dir = project_root / "squads"
    domains = {}

    if not squads_dir.exists():
        return domains

    for squad_dir in sorted(squads_dir.iterdir()):
        if not squad_dir.is_dir():
            continue

        squad_name = squad_dir.name

        # Skip dispatch itself — it's the orchestrator, not a domain
        if squad_name == "dispatch":
            continue

        config = read_yaml_safe(squad_dir / "config.yaml")

        # Discover agents
        agents = scan_dir_names(squad_dir / "agents")

        # Discover tasks
        tasks = scan_dir_names(squad_dir / "tasks")

        # Discover KB files
        kb_files = find_kb_files(squad_dir / "data", project_root)

        # Get entry agent from config
        pack_config = config.get("pack", config)
        entry_agent = config.get("entry_agent", agents[0] if agents else None)

        # Build triggers from known map or derive from agent/task names
        triggers = DOMAIN_KEYWORD_MAP.get(squad_name, {})
        primary_triggers = triggers.get("primary", _derive_keywords(squad_name, agents, tasks))
        secondary_triggers = triggers.get("secondary", [])

        domain_id = _normalize_domain_id(squad_name)

        domains[domain_id] = {
            "source": f"squads/{squad_name}",
            "description": pack_config.get("description", f"Squad: {squad_name}"),
            "triggers": {
                "primary": primary_triggers,
                "secondary": secondary_triggers,
                "weight_primary": 3,
                "weight_secondary": 1,
            },
            "agents": {
                "primary": f"/{squad_name}:agents:{entry_agent}" if entry_agent else None,
                "squad": squad_name,
                "all_agents": [f"/{squad_name}:agents:{a}" for a in agents],
            },
            "kb_files": kb_files[:5],  # Limit to top 5
            "enrichment": ENRICHMENT_DEFAULTS.get(squad_name, "STANDARD"),
            "default_model": MODEL_DEFAULTS.get(squad_name, "haiku"),
            "stats": {
                "agents": len(agents),
                "tasks": len(tasks),
            },
        }

    return domains


def scan_aios_core(project_root: Path) -> dict:
    """Scan .aios-core/ for development agents and create domains."""
    aios_dir = project_root / ".aios-core"
    domains = {}

    if not aios_dir.exists():
        return domains

    # Scan development agents
    agents_dir = aios_dir / "development" / "agents"
    if agents_dir.exists():
        found_agents = scan_dir_names(agents_dir)
    else:
        found_agents = []

    # For each known agent mapping, create a domain entry if agent exists
    for agent_id, config in AIOS_AGENT_DOMAINS.items():
        # Check if agent file exists (some agents may be standalone commands)
        agent_file_exists = agent_id in found_agents or (agents_dir / f"{agent_id}.md").exists()

        # Find context/KB files
        kb_files = config.get("kb_files", [])
        context_file = aios_dir / "context" / f"{agent_id}.md"
        if context_file.exists():
            kb_files = [str(context_file.relative_to(project_root)).replace("\\", "/")] + kb_files

        domain_id = _normalize_domain_id(agent_id)

        domains[domain_id] = {
            "source": ".aios-core",
            "triggers": {
                "primary": config["triggers_primary"],
                "secondary": config["triggers_secondary"],
                "weight_primary": 3,
                "weight_secondary": 1,
            },
            "agents": {
                "primary": f"@{agent_id}",
                "squad": None,
            },
            "kb_files": kb_files,
            "enrichment": config["enrichment"],
            "default_model": config["model"],
        }

        if "note" in config:
            domains[domain_id]["note"] = config["note"]

    return domains


def scan_organization_domain() -> dict:
    """Static domain for file organization tasks (worker scripts only)."""
    return {
        "organization": {
            "source": "built-in",
            "triggers": {
                "primary": ["organizar", "index", "estruturar", "renomear", "mover"],
                "secondary": ["pasta", "arquivo", "gitkeep", "cleanup", "folder"],
                "weight_primary": 3,
                "weight_secondary": 1,
            },
            "agents": {
                "primary": None,
                "squad": None,
            },
            "kb_files": ["CLAUDE.md"],
            "enrichment": "MINIMAL",
            "default_model": None,
            "note": "Worker scripts only, no agent needed",
        }
    }


def load_manual_overrides(project_root: Path) -> dict:
    """Load manual overrides from separate file."""
    overrides_path = project_root / "squads" / "dispatch" / "data" / "manual-overrides.yaml"
    if not overrides_path.exists():
        return {}
    return read_yaml_safe(overrides_path).get("overrides", {})


def validate_paths(domains: dict, project_root: Path) -> list[str]:
    """Validate that all referenced paths exist. Return warnings."""
    warnings = []
    for domain_id, domain in domains.items():
        for kb_file in domain.get("kb_files", []):
            full_path = project_root / kb_file
            if not full_path.exists():
                warnings.append(f"[WARN] Domain '{domain_id}': KB file not found: {kb_file}")
    return warnings


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _normalize_domain_id(name: str) -> str:
    """Normalize a name into a domain ID (snake_case)."""
    return name.replace("-", "_").lower()


def _derive_keywords(squad_name: str, agents: list[str], tasks: list[str]) -> list[str]:
    """Derive trigger keywords from squad/agent/task names."""
    keywords = [squad_name.replace("-", " ")]
    for name in agents[:3]:
        keywords.append(name.replace("-", " "))
    for name in tasks[:5]:
        clean = name.replace("-", " ").replace("create ", "").replace("build ", "")
        if clean not in keywords:
            keywords.append(clean)
    return keywords[:10]


# ─────────────────────────────────────────────────────────────────────────────
# OUTPUT GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_registry_yaml(domains: dict, overrides: dict) -> str:
    """Generate the complete domain-registry.yaml content."""
    lines = [HEADER.format(timestamp=datetime.now().isoformat())]

    # Apply overrides (merge on top of auto-generated)
    for domain_id, override in overrides.items():
        if domain_id in domains:
            # Merge: override takes precedence
            for key, value in override.items():
                domains[domain_id][key] = value
        else:
            # New domain from override
            domains[domain_id] = override

    lines.append("domains:")

    for domain_id in sorted(domains.keys()):
        d = domains[domain_id]
        lines.append(f"  {domain_id}:")

        # Source
        source = d.get("source", "unknown")
        lines.append(f"    source: \"{source}\"")

        # Description (if present)
        if "description" in d:
            desc = d["description"]
            if len(desc) > 80:
                lines.append(f"    description: >-")
                lines.append(f"      {desc}")
            else:
                lines.append(f"    description: \"{desc}\"")

        # Triggers
        triggers = d.get("triggers", {})
        lines.append(f"    triggers:")
        lines.append(f"      primary: {_format_list(triggers.get('primary', []))}")
        lines.append(f"      secondary: {_format_list(triggers.get('secondary', []))}")
        lines.append(f"      weight_primary: {triggers.get('weight_primary', 3)}")
        lines.append(f"      weight_secondary: {triggers.get('weight_secondary', 1)}")

        # Agents
        agents = d.get("agents", {})
        lines.append(f"    agents:")
        primary = agents.get("primary")
        lines.append(f"      primary: \"{primary}\"" if primary else f"      primary: null")
        squad = agents.get("squad")
        lines.append(f"      squad: \"{squad}\"" if squad else f"      squad: null")
        if "all_agents" in agents:
            lines.append(f"      all_agents: {_format_list(agents['all_agents'])}")

        # KB files
        kb_files = d.get("kb_files", [])
        if kb_files:
            lines.append(f"    kb_files:")
            for kb in kb_files:
                lines.append(f"      - \"{kb}\"")

        # Enrichment & model
        lines.append(f"    enrichment: {d.get('enrichment', 'STANDARD')}")
        model = d.get("default_model")
        lines.append(f"    default_model: {model}" if model else f"    default_model: null")

        # Note
        if "note" in d:
            lines.append(f"    note: \"{d['note']}\"")

        # Stats
        if "stats" in d:
            stats = d["stats"]
            lines.append(f"    stats:")
            lines.append(f"      agents: {stats.get('agents', 0)}")
            lines.append(f"      tasks: {stats.get('tasks', 0)}")

        lines.append("")

    # Scoring algorithm (static)
    lines.append("""# ═══════════════════════════════════════════════════════════════════════════════
# DOMAIN SCORING ALGORITHM
# ═══════════════════════════════════════════════════════════════════════════════

scoring:
  algorithm: "weighted_keyword_match"
  tie_breaking:
    - "Prioritize AUTOMATION over MARKETING (execution before creation)"
    - "If still tied, use order of appearance in text"
  multi_domain:
    behavior: "Detect ALL domains, assign tasks to respective agents"
    example: "Story with copy + AC tasks -> copy tasks to copy-chief, AC tasks to ac-automation"

# ═══════════════════════════════════════════════════════════════════════════════
# BUSINESS CONTEXT (Conditional Loading)
# ═══════════════════════════════════════════════════════════════════════════════

business_context:
  triggers: [lançamento, lancamento, abertura, carrinho, live, campanha]
  source_dir: "plan/campaigns/"
  priority_files: [tom-de-voz.md, icp.md, ofertas.md, datas.md]
  max_tokens: 2000
  condition: "Load IF AND ONLY IF triggers present"
""")

    # Summary
    total = len(domains)
    squad_count = sum(1 for d in domains.values() if d.get("agents", {}).get("squad"))
    aios_count = sum(1 for d in domains.values() if d.get("source") == ".aios-core")
    lines.append(f"# Summary: {total} domains ({squad_count} from squads, {aios_count} from .aios-core)")

    return "\n".join(lines)


def _format_list(items: list) -> str:
    """Format a list as YAML inline list."""
    if not items:
        return "[]"
    return "[" + ", ".join(f'"{i}"' for i in items) + "]"


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Build domain registry by scanning the project ecosystem"
    )
    parser.add_argument(
        "--output",
        default="squads/dispatch/data/domain-registry.yaml",
        help="Output file path (default: squads/dispatch/data/domain-registry.yaml)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing file")
    parser.add_argument("--project-root", default=".", help="Project root directory")
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    print(f"Scanning project: {project_root}")

    # ── Phase 1: Scan all sources ──
    squad_domains = scan_squads(project_root)
    aios_domains = scan_aios_core(project_root)
    org_domain = scan_organization_domain()
    overrides = load_manual_overrides(project_root)

    # ── Phase 2: Merge (squads take precedence over aios-core for same domain) ──
    all_domains = {}
    all_domains.update(aios_domains)
    all_domains.update(org_domain)
    all_domains.update(squad_domains)  # Squads override aios-core if same domain ID

    # ── Phase 3: Validate paths ──
    warnings = validate_paths(all_domains, project_root)
    for w in warnings:
        print(w, file=sys.stderr)

    # ── Phase 4: Generate output ──
    output = generate_registry_yaml(all_domains, overrides)

    # ── Phase 5: Report ──
    total = len(all_domains)
    print(f"Discovered: {len(squad_domains)} squad domains, {len(aios_domains)} aios-core domains, 1 built-in")
    print(f"Total: {total} domains")
    if overrides:
        print(f"Manual overrides applied: {len(overrides)}")
    if warnings:
        print(f"Warnings: {len(warnings)} (broken paths)")

    if args.dry_run:
        print("\n--- DRY RUN ---")
        print(output)
    else:
        output_path = project_root / args.output
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Registry written to: {output_path}")

    # Return exit code
    sys.exit(0)


if __name__ == "__main__":
    main()
