#!/usr/bin/env python3
"""
Dispatch Squad — Build Command Registry
Law #1: CODE > LLM — Scanning files is deterministic.
Law #4: SLASH COMMAND MAP — Registry generated by SCRIPT, not LLM.

Scans all squads/, .claude/commands/, and .aios-core/ to build a complete
command registry (command-registry.yaml) mapping every available
slash command to its agent, model, and purpose.

Graceful degradation: works even if .aios-core/ or squads/ don't exist.

Usage:
    python squads/dispatch/scripts/build-command-registry.py
    python squads/dispatch/scripts/build-command-registry.py --output squads/dispatch/data/command-registry.yaml
    python squads/dispatch/scripts/build-command-registry.py --dry-run
"""

import argparse
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None


def scan_squad_configs(project_root: Path) -> dict:
    """Scan all squad config.yaml files for agent/task registries."""
    squads_dir = project_root / "squads"
    registry = {}

    if not squads_dir.exists():
        return registry

    for squad_dir in sorted(squads_dir.iterdir()):
        if not squad_dir.is_dir():
            continue

        config_path = squad_dir / "config.yaml"
        if not config_path.exists():
            continue

        squad_name = squad_dir.name
        registry[squad_name] = {
            "agents": [],
            "tasks": [],
        }

        # Scan agents directory
        agents_dir = squad_dir / "agents"
        if agents_dir.exists():
            for agent_file in sorted(agents_dir.glob("*.md")):
                agent_name = agent_file.stem
                registry[squad_name]["agents"].append({
                    "name": agent_name,
                    "path": f"/{squad_name}:agents:{agent_name}",
                    "file": str(agent_file.relative_to(project_root)).replace("\\", "/"),
                })

        # Scan tasks directory
        tasks_dir = squad_dir / "tasks"
        if tasks_dir.exists():
            for task_file in sorted(tasks_dir.glob("*.md")):
                task_name = task_file.stem
                registry[squad_name]["tasks"].append({
                    "name": task_name,
                    "path": f"/{squad_name}:tasks:{task_name}",
                    "file": str(task_file.relative_to(project_root)).replace("\\", "/"),
                })
            # Scan subdirectories (e.g., tasks/plf/, tasks/brunson/)
            for sub_dir in sorted(tasks_dir.iterdir()):
                if sub_dir.is_dir():
                    for task_file in sorted(sub_dir.glob("*.md")):
                        task_name = f"{sub_dir.name}/{task_file.stem}"
                        registry[squad_name]["tasks"].append({
                            "name": task_name,
                            "path": f"/{squad_name}:tasks:{sub_dir.name}:{task_file.stem}",
                            "file": str(task_file.relative_to(project_root)).replace("\\", "/"),
                        })

    return registry


def scan_claude_commands(project_root: Path) -> dict:
    """Scan .claude/commands/ for IDE command definitions."""
    commands_dir = project_root / ".claude" / "commands"
    registry = {}

    if not commands_dir.exists():
        return registry

    for squad_dir in sorted(commands_dir.iterdir()):
        if not squad_dir.is_dir():
            continue

        squad_name = squad_dir.name

        # Scan for task commands
        tasks_dir = squad_dir / "tasks"
        if tasks_dir.exists():
            if squad_name not in registry:
                registry[squad_name] = {"agents": [], "tasks": []}
            for task_file in sorted(tasks_dir.glob("*.md")):
                task_name = task_file.stem
                path = f"/{squad_name}:tasks:{task_name}"
                # Check if already in registry
                existing = [t["path"] for t in registry.get(squad_name, {}).get("tasks", [])]
                if path not in existing:
                    registry.setdefault(squad_name, {"agents": [], "tasks": []})["tasks"].append({
                        "name": task_name,
                        "path": path,
                        "file": str(task_file.relative_to(project_root)).replace("\\", "/"),
                        "source": "claude_commands",
                    })

    return registry


def scan_aios_core_agents(project_root: Path) -> dict:
    """Scan .aios-core/development/agents/ for agent definitions."""
    agents_dir = project_root / ".aios-core" / "development" / "agents"
    registry = {}

    if not agents_dir.exists():
        return registry

    squad_name = "AIOS"
    registry[squad_name] = {"agents": [], "tasks": []}

    for agent_file in sorted(agents_dir.glob("*.md")):
        agent_name = agent_file.stem
        registry[squad_name]["agents"].append({
            "name": agent_name,
            "path": f"/AIOS:agents:{agent_name}",
            "file": str(agent_file.relative_to(project_root)).replace("\\", "/"),
            "source": "aios_core",
        })

    return registry


def scan_aios_core_tasks(project_root: Path) -> dict:
    """Scan .aios-core/development/tasks/ and .aios-core/marketing/tasks/ for task definitions."""
    registry = {}

    task_dirs = [
        project_root / ".aios-core" / "development" / "tasks",
        project_root / ".aios-core" / "marketing" / "tasks",
    ]

    squad_name = "AIOS"

    for tasks_dir in task_dirs:
        if not tasks_dir.exists():
            continue

        if squad_name not in registry:
            registry[squad_name] = {"agents": [], "tasks": []}

        for task_file in sorted(tasks_dir.glob("*.md")):
            task_name = task_file.stem
            # Skip deprecated files
            if task_name.startswith("_deprecated"):
                continue
            path = f"/AIOS:tasks:{task_name}"
            existing_paths = {t["path"] for t in registry[squad_name].get("tasks", [])}
            if path not in existing_paths:
                registry[squad_name]["tasks"].append({
                    "name": task_name,
                    "path": path,
                    "file": str(task_file.relative_to(project_root)).replace("\\", "/"),
                    "source": "aios_core",
                })

        # Scan subdirectories
        for sub_dir in sorted(tasks_dir.iterdir()):
            if sub_dir.is_dir():
                for task_file in sorted(sub_dir.glob("*.md")):
                    task_name = f"{sub_dir.name}/{task_file.stem}"
                    path = f"/AIOS:tasks:{sub_dir.name}:{task_file.stem}"
                    existing_paths = {t["path"] for t in registry[squad_name].get("tasks", [])}
                    if path not in existing_paths:
                        registry[squad_name]["tasks"].append({
                            "name": task_name,
                            "path": path,
                            "file": str(task_file.relative_to(project_root)).replace("\\", "/"),
                            "source": "aios_core",
                        })

    return registry


def merge_registries(squad_registry: dict, command_registry: dict) -> dict:
    """Merge squad and command registries, deduplicating."""
    merged = dict(squad_registry)
    for squad_name, data in command_registry.items():
        if squad_name not in merged:
            merged[squad_name] = data
        else:
            existing_paths = {t["path"] for t in merged[squad_name].get("tasks", [])}
            for task in data.get("tasks", []):
                if task["path"] not in existing_paths:
                    merged[squad_name]["tasks"].append(task)
    return merged


def generate_registry_text(registry: dict) -> str:
    """Generate YAML-formatted registry text."""
    lines = [
        "# ═══════════════════════════════════════════════════════════════════════════════",
        "# COMMAND REGISTRY — Auto-generated by build-command-registry.py",
        "# DO NOT EDIT MANUALLY — run: python squads/dispatch/scripts/build-command-registry.py",
        f"# Generated: {__import__('datetime').datetime.now().isoformat()}",
        "# ═══════════════════════════════════════════════════════════════════════════════",
        "",
        "commands:",
    ]

    total_agents = 0
    total_tasks = 0

    for squad_name in sorted(registry.keys()):
        data = registry[squad_name]
        agents = data.get("agents", [])
        tasks = data.get("tasks", [])

        lines.append(f"  {squad_name}:")

        if agents:
            lines.append("    agents:")
            for agent in agents:
                lines.append(f'      - path: "{agent["path"]}"')
                lines.append(f'        file: "{agent["file"]}"')
                total_agents += 1

        if tasks:
            lines.append("    tasks:")
            for task in tasks:
                lines.append(f'      - path: "{task["path"]}"')
                lines.append(f'        file: "{task["file"]}"')
                total_tasks += 1

        lines.append("")

    lines.append(f"# Summary: {len(registry)} squads, {total_agents} agents, {total_tasks} tasks")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Build dispatch command registry")
    parser.add_argument(
        "--output",
        default="squads/dispatch/data/command-registry.yaml",
        help="Output file path",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print without writing")
    parser.add_argument("--root", default=".", help="Project root directory")
    args = parser.parse_args()

    project_root = Path(args.root).resolve()

    print(f"Scanning project: {project_root}")

    squad_registry = scan_squad_configs(project_root)
    command_registry = scan_claude_commands(project_root)
    aios_agents = scan_aios_core_agents(project_root)
    aios_tasks = scan_aios_core_tasks(project_root)

    # Merge all sources: squads + claude_commands + aios_core
    merged = merge_registries(squad_registry, command_registry)
    merged = merge_registries(merged, aios_agents)
    merged = merge_registries(merged, aios_tasks)

    output = generate_registry_text(merged)

    total_squads = len(merged)
    total_agents = sum(len(d.get("agents", [])) for d in merged.values())
    total_tasks = sum(len(d.get("tasks", [])) for d in merged.values())

    print(f"Found: {total_squads} squads, {total_agents} agents, {total_tasks} tasks")

    if args.dry_run:
        print("\n--- DRY RUN ---")
        print(output)
    else:
        output_path = project_root / args.output
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Registry written to: {output_path}")


if __name__ == "__main__":
    main()
