import type { BuscaResult, ValidationErrors, Setor } from "../../types";
import type { TermValidation } from "../hooks/useSearchFilters";
import type { StatusLicitacao } from "./StatusFilter";
import type { Esfera } from "../../components/EsferaFilter";
import type { Municipio } from "../../components/MunicipioFilter";

export interface SearchFormProps {
  setores: Setor[];
  setoresLoading: boolean;
  setoresError: boolean;
  setoresUsingFallback: boolean;
  setoresUsingStaleCache: boolean;
  staleCacheAge: number | null;
  setoresRetryCount: number;
  setorId: string;
  setSetorId: (id: string) => void;
  fetchSetores: (attempt?: number) => Promise<void>;
  searchMode: "setor" | "termos";
  setSearchMode: (mode: "setor" | "termos") => void;
  modoBusca: "abertas" | "publicacao";
  dateLabel: string;
  termosArray: string[];
  termoInput: string;
  setTermoInput: (input: string) => void;
  termValidation: TermValidation | null;
  addTerms: (newTerms: string[]) => void;
  removeTerm: (term: string) => void;
  ufsSelecionadas: Set<string>;
  toggleUf: (uf: string) => void;
  toggleRegion: (regionUfs: string[]) => void;
  selecionarTodos: () => void;
  limparSelecao: () => void;
  dataInicial: string;
  setDataInicial: (date: string) => void;
  dataFinal: string;
  setDataFinal: (date: string) => void;
  validationErrors: ValidationErrors;
  canSearch: boolean;
  searchLabel: string;
  locationFiltersOpen: boolean;
  setLocationFiltersOpen: (open: boolean) => void;
  advancedFiltersOpen: boolean;
  setAdvancedFiltersOpen: (open: boolean) => void;
  esferas: Esfera[];
  setEsferas: (e: Esfera[]) => void;
  municipios: Municipio[];
  setMunicipios: (m: Municipio[]) => void;
  status: StatusLicitacao;
  setStatus: (s: StatusLicitacao) => void;
  modalidades: number[];
  setModalidades: (m: number[]) => void;
  valorMin: number | null;
  setValorMin: (v: number | null) => void;
  valorMax: number | null;
  setValorMax: (v: number | null) => void;
  setValorValid: (valid: boolean) => void;
  loading: boolean;
  buscar: () => void;
  searchButtonRef: React.RefObject<HTMLButtonElement | null>;
  result: BuscaResult | null;
  handleSaveSearch: () => void;
  isMaxCapacity: boolean;
  planInfo: { plan_name: string; capabilities: { max_history_days: number } } | null;
  onShowUpgradeModal: (plan?: string, source?: string) => void;
  clearResult: () => void;
  customizeOpen: boolean;
  setCustomizeOpen: (open: boolean) => void;
  isTrialExpired?: boolean;
  isGracePeriod?: boolean;
  showFirstUseTip?: boolean;
  onDismissFirstUseTip?: () => void;
}
