#!/usr/bin/env bash
# STORY-222: Generate TypeScript types from backend OpenAPI schema.
#
# Usage:
#   ./scripts/generate-api-types.sh              # Fetch from running backend
#   ./scripts/generate-api-types.sh --check      # Check if generated types are up-to-date
#   OPENAPI_URL=http://... ./scripts/generate-api-types.sh  # Custom URL
#
# Prerequisites:
#   - Backend running at $OPENAPI_URL (default: http://localhost:8000)
#   - npx available (openapi-typescript installed as devDep in frontend/)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
OUTPUT_FILE="$FRONTEND_DIR/app/api-types.generated.ts"
OPENAPI_URL="${OPENAPI_URL:-http://localhost:8000/openapi.json}"

# Header for generated file
HEADER="/* eslint-disable */
/* AUTO-GENERATED — DO NOT EDIT MANUALLY.
 * Generated by scripts/generate-api-types.sh from backend OpenAPI schema.
 * Re-run: npm run generate:api-types (or ./scripts/generate-api-types.sh)
 * Source: $OPENAPI_URL
 */"

echo "=== STORY-222: OpenAPI → TypeScript Codegen ==="
echo "Source:  $OPENAPI_URL"
echo "Output:  $OUTPUT_FILE"

# Fetch OpenAPI schema to verify backend is reachable
echo ""
echo "Fetching OpenAPI schema..."
if ! curl -sf "$OPENAPI_URL" > /dev/null 2>&1; then
  echo "ERROR: Cannot reach backend at $OPENAPI_URL"
  echo "Make sure the backend is running: cd backend && uvicorn main:app --port 8000"
  exit 1
fi
echo "Backend is reachable."

# Generate types
echo "Generating TypeScript types..."
cd "$FRONTEND_DIR"

# Generate to temp file first
TEMP_FILE=$(mktemp)
npx openapi-typescript "$OPENAPI_URL" --output "$TEMP_FILE" 2>&1

# Prepend header
{
  echo "$HEADER"
  echo ""
  cat "$TEMP_FILE"
} > "${OUTPUT_FILE}.tmp"
mv "${OUTPUT_FILE}.tmp" "$OUTPUT_FILE"
rm -f "$TEMP_FILE"

echo "Generated: $OUTPUT_FILE"

# --check mode: verify generated types match existing file
if [[ "${1:-}" == "--check" ]]; then
  echo ""
  echo "Checking if generated types are up-to-date..."

  # Generate to a comparison file
  COMPARE_FILE=$(mktemp)
  npx openapi-typescript "$OPENAPI_URL" --output "$COMPARE_FILE" 2>&1

  {
    echo "$HEADER"
    echo ""
    cat "$COMPARE_FILE"
  } > "${COMPARE_FILE}.full"

  if diff -q "$OUTPUT_FILE" "${COMPARE_FILE}.full" > /dev/null 2>&1; then
    echo "Types are up-to-date."
    rm -f "$COMPARE_FILE" "${COMPARE_FILE}.full"
  else
    echo "ERROR: Generated types are out of date!"
    echo "Run: npm run generate:api-types"
    rm -f "$COMPARE_FILE" "${COMPARE_FILE}.full"
    exit 1
  fi
fi

# Type-check the generated file
echo ""
echo "Running TypeScript check..."
npx tsc --noEmit --pretty 2>&1 || {
  echo ""
  echo "WARNING: TypeScript errors detected. Review generated types."
  exit 1
}

echo ""
echo "Done. Types generated and validated successfully."
